### ISSUE TITLE
errors out when starting demo

### ISSUE THREAD

**Issue by jakeburden** [yoshuawuyts/cool-crusts#1]
Greetings 👋  👋   I really like the idea of this architecture!

just spotted this error when trying the demo out directly after cloning down and running npm install

```
~/cool-crusts master $ npm start

> cool-crusts@1.0.0 start /Users/Jake/cool-crusts
> nodemon . -i client.js | merry-pretty

[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node .`
{"logKey":"3cdebba00d8c3143c95926deb7c93b15189336a5fc6d68e60776987a4be07a8a"}
buffer.js:287
  throw new TypeError(kFromErrorMsg);
  ^

TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at fromObject (buffer.js:287:9)
    at Function.Buffer.from (buffer.js:133:10)
    at new Buffer (buffer.js:112:17)
    at MerkleGenerator.next (/Users/Jake/cool-crusts/node_modules/merkle-tree-stream/generator.js:26:38)
    at Feed._append (/Users/Jake/cool-crusts/node_modules/hypercore/lib/feed.js:699:30)
    at /Users/Jake/cool-crusts/node_modules/hypercore/lib/feed.js:747:10
    at apply (/Users/Jake/cool-crusts/node_modules/thunky/index.js:16:28)
    at /Users/Jake/cool-crusts/node_modules/thunky/index.js:20:25
    at done (/Users/Jake/cool-crusts/node_modules/hypercore/lib/feed.js:668:5)
    at openStorage (/Users/Jake/cool-crusts/node_modules/hypercore/lib/feed.js:659:31)
[nodemon] app crashed - waiting for file changes before starting...
^C
~/cool-crusts master $
```

**Comment by yoshuawuyts** [comment]
oh cool - looks like someone pushed a breaking change somewhere I think hmmm

**Comment by yoshuawuyts** [comment]
ohhhh yeah no I remember now - it's `bole` that goes into object mode whenever a feed is attached and it like breaks stuff - yeahhhhh that's not good hah - so the dirty fix is to pass it through a json stringify stream - the proper mode is to prevent `bole` from going into objectmode in times like these. Oooops, shoulda mentioned that haha

**Comment by yoshuawuyts** [comment]
ok fixed it! - had to disable object mode on `hypercore`
